# db url
#spring.datasource.url=jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul

# db name
#spring.datasource.username=root

# db password
#spring.datasource.password=securus1234

# query print
#spring.jpa.show-sql=true

server :
  port : 80
  #session :
  #   timeout : 600

spring :
  #session :
  #   timeout : 600
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8

    #°³¹ß
    username: root
    password: securus1234

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false

  thymeleaf:
    cache: false

  mybatis:
    config-location: classpath:mybatis-config.xml
    configuration:
      map-underscore-to-camel-case: true

